import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import '../public/style/global.css'
//font opmization
const rubik = Rubik({ subsets: ["latin"], 
weight: ['500', '700']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
